version: '3.8'
services:
  grafana:
    image: grafana/grafana:main-ubuntu
    container_name: grafana
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - '443:443'
volumes:
  grafana-storage: {}
