name: CI for Grafana Container

on:
  push:
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - 'useful-scripts/install_docker_debian.sh'
      - 'useful-scripts/install_docker_ubuntu.sh'
      - 'certs/*'
  pull_request:
    paths-ignore:
      - '.gitignore'
      - '*.md'
      - 'LICENSE'
      - 'useful-scripts/install_docker_debian.sh'
      - 'useful-scripts/install_docker_ubuntu.sh'
      - 'certs/*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate SSL/TLS certificates
        run: |
          mkdir -p certs
          openssl genrsa -out certs/server.key 2048
          openssl req -new -key certs/server.key -out certs/server.csr -subj "/CN=localhost"
          openssl x509 -req -days 365 -in certs/server.csr -signkey certs/server.key -out certs/server.crt

      - name: Update docker-compose.yml with service dependencies
        run: |
          # Add depends_on to ensure Nginx starts after Grafana
          sed -i '/image: nginx:latest/a\    depends_on:\n      - grafana' docker-compose.yml
          # Update to use specific image versions
          sed -i 's|image: nginx:latest|image: nginx:1.21.6|g' docker-compose.yml

      - name: Start services
        run: docker-compose up -d

      - name: Check if containers are running
        run: docker ps -a

      - name: Check docker-compose logs
        run: docker-compose logs

      - name: Wait longer for services to fully start
        run: sleep 60

      - name: Verify Nginx configuration
        run: docker-compose exec -T nginx nginx -t

      - name: Test connection to Nginx
        run: |
          # Try connecting to Nginx directly
          curl -v --retry 10 --retry-delay 10 --retry-connrefused --insecure https://localhost || true

      - name: Test connection to Grafana
        run: |
          # Try connecting to Grafana directly
          curl -v --retry 5 --retry-delay 5 --retry-connrefused http://localhost:3000 || true

      - name: Stop and remove services
        run: docker-compose down -v
