name: CI for Grafana Container

on:
  push:
  pull_request:

jobs:
  build-and-test-grafana-docker-compose:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Generate SSL/TLS certificates
      run: |
        mkdir -p certs
        openssl genrsa -out certs/server.key 2048
        openssl req -new -key certs/server.key -out certs/server.csr -subj "/CN=localhost"
        openssl x509 -req -days 365 -in certs/server.csr -signkey certs/server.key -out certs/server.crt

    - name: Pull Docker images
      run: |
        docker pull grafana/grafana:main-ubuntu
        docker pull nginx:latest

    - name: Start services
      run: docker-compose up -d

    - name: Verify Grafana service
      run: |
        sleep 30
        curl --retry 5 --retry-delay 5 --retry-connrefused http://localhost:3000

    - name: Stop and remove services
      run: docker-compose down -v

    - name: Remove Docker images
      run: |
        docker image rm grafana/grafana:main-ubuntu nginx:latest
